locals {
  harness_secrets = var.enable_harness_k8s_connector ? {
    "${var.gke_cluster_name}_cluster_ca_certificate" = {
      description = "secret generated by terraform"
      tags        = var.tags
      secret      = base64decode(module.gcp.gke.cluster_ca_certificate)
    }
    "${var.gke_cluster_name}_service_account_token" = {
      description = "secret generated by terraform"
      tags        = var.tags
      secret      = lookup(module.kubernetes.service_account_token["harness-service-account-token"].data, "token")
    }
  } : {}
  kubernetes_connector = var.enable_harness_k8s_connector ? {
    "${var.gke_cluster_name}" = {
      description        = "terraform generated k8s connector"
      tags               = var.tags
      project_id         = "" # harness project_id
      org_id             = "" # harness org_id
      delegate_selectors = []
      service_account = {
        credentials = {
          master_url                = "https://${module.gcp.gke.endpoint}"
          service_account_token_ref = "${var.gke_cluster_name}_service_account_token"
        }
      }
      username_password     = {}
      inherit_from_delegate = {}
    }
  } : {}
  kubernetes_ccm_connector = var.enable_harness_ccm_connector ? {
    "${var.gke_cluster_name}" = {
      description        = "terraform generated k8s connector"
      tags               = var.tags
      project_id         = ""
      org_id             = ""
      delegate_selectors = []
      features_enabled   = ["VISIBILITY"]
    }
  } : {}
}
